### ISSUE TITLE
请问这个两个usb3.0一个usb2.0都能用吗

### ISSUE THREAD

**Issue by yuaneuro** [JiangHoumin/Dell_G3_3579_Hackintosh#7]
机型Dell 3579
i5-8300h +8g +128g +1t + GTX10504G

**Comment by JiangHoumin** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        
            
        
    
    
        所有usb端口都可以用
        
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                Houmin Jiang
                            
                    
                        
                            
                                    jhmhehe@gmail.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    在2019年6月9日 20:35，yuaneuro<notifications@github.com> 写道： 


机型Dell 3579

i5-8300h +8g +128g +1t + GTX10504G



—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by yuaneuro** [comment]
好的     谢谢   回复得真快

**Comment by JiangHoumin** [comment]
都可以用 naruto jiang 邮箱：jhmhehe@gmail.com 签名由 网易邮箱大师 定制 在2019年06月09日 20:36，yuaneuro 写道： 好的 谢谢 回复得真快 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.
