### ISSUE TITLE
关于黑苹果网卡的购买

### ISSUE THREAD

**Issue by yuaneuro** [JiangHoumin/Dell_G3_3579_Hackintosh#8]
请问你在哪里买的黑苹果网卡，求推荐或购买链接，谢谢

**Comment by JiangHoumin** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        bcm94352z 淘宝
        
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                Houmin Jiang
                            
                    
                        
                            
                                    jhmhehe@gmail.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    在2019年6月10日 13:56，yuaneuro<notifications@github.com> 写道： 


请问你在哪里买的黑苹果网卡，求推荐或购买链接，谢谢



—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by yuaneuro** [comment]
我在淘宝找了有很多，不同价格的也，不知道买哪个，求推荐个链接

**Comment by JiangHoumin** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        https://item.taobao.com/item.htm?spm=a1z09.2.0.0.c8822e8dlfupVK&id=524391843184&_u=ar6q3nd879b
            
        
    我当时买150左右，现在涨到298了 真黑心商人
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                Houmin Jiang
                            
                    
                        
                            
                                    jhmhehe@gmail.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    在2019年6月10日 14:00，yuaneuro<notifications@github.com> 写道： 


我在淘宝找了有很多，不同价格的也，不知道买哪个，求推荐个链接



—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.
